### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by dinan5** [sebr/bhyve-home-assistant#231] opened 2023-12-15 19:55 UTC
**Describe the bug**
Multiple times per day I get the following error:
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bhyve/pybhyve/websocket.py", line 57, in _ping
    await self._ws.send_str(json.dumps({"event": "ping"}))
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 165, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 628, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Expected behaviour**
No error

**BHyve devices**
two devices - Smart Hose Tap, Orbit Sprinkler Controller

**Device Diagnostics**

**Comment by sebr** [comment] 2024-04-23 06:26
Dupe of #156

**Closed by sebr** 2024-04-23 06:26 UTC
