### ISSUE TITLE
Enhancement time "Time left to run" attribute

### ISSUE THREAD

**Issue by darrenblanchard** [sebr/bhyve-home-assistant#186] opened 2023-05-13 10:34 UTC
Is it possible to retrieve the timer "time left to run" attribute? If I log into my Bhyve dashboard while the timer is running, I can see the time left until the timer will shut off, I currently use Node-Red and create timer entities when the switch gets turned on, but it gets messy when updates come through sometimes.

Thanks

**Comment by sebr** [comment] 2023-05-27 08:53
Dupe of #185

**Closed by sebr** 2023-05-27 08:53 UTC
